### ISSUE TITLE
Compilation fails with clang19

### ISSUE THREAD

**Issue by outpaddling** [COMBINE-lab/salmon#988]
Salmon 1.10.2 and 1.10.3 both fail to compile with clang19 (under FreeBSD 13.5 and 14.3).  They build fine under clang18.

The first problem I hit was in external/pufferfish/external/twopaco/graphconstructor/candidateoccurence.h and seems to be due to the fact that atomic objects are not copyable.  

```
/usr/ports/wip/salmon/work/salmon-1.10.3/external/pufferfish/external/twopaco/graphconstructor/candidateoccurence.h:61:11: error: overload resolution selected deleted operator '='
   61 |                         count_ = toCopy.count_;
      |                         ~~~~~~ ^ ~~~~~~~~~~~~~
/usr/include/c++/v1/__atomic/atomic.h:58:11: note: candidate function has been explicitly deleted
   58 |   atomic& operator=(const atomic&)          = delete;
      |           ^
/usr/include/c++/v1/__atomic/atomic.h:59:11: note: candidate function has been explicitly deleted
   59 |   atomic& operator=(const atomic&) volatile = delete;
      |           ^
/usr/include/c++/v1/__atomic/atomic.h:49:29: note: candidate function           
   49 |   _LIBCPP_HIDE_FROM_ABI _Tp operator=(_Tp __d) volatile _NOEXCEPT {
      |                             ^
/usr/include/c++/v1/__atomic/atomic.h:53:29: note: candidate function           
   53 |   _LIBCPP_HIDE_FROM_ABI _Tp operator=(_Tp __d) _NOEXCEPT {
      |                             ^
1 error generated.                                                              
gmake[2]: *** [external/pufferfish/external/twopaco/graphconstructor/CMakeFiles/
```

I worked around it with the following patch:

```
--- external/pufferfish/external/twopaco/graphconstructor/candidateoccurence.h.orig     2025-07-26 13:01:27 UTC
+++ external/pufferfish/external/twopaco/graphconstructor/candidateoccurence.h
@@ -58,7 +58,7 @@ namespace TwoPaCo
                const CandidateOccurence & operator = (const CandidateOccurence & toCopy)
                {
                        body_ = toCopy.body_;
-                       count_ = toCopy.count_;
+                       count_.store(toCopy.count_.load(std::memory_order_relaxed));
                }
 
                void Inc()
```

I then hit the same error describe in https://github.com/COMBINE-lab/salmon/issues/987.

**Comment by outpaddling** [comment]
FYI, I solved the libdivide issue and another issue with eigen3 by unbundling them (i.e. using libdivide and eigen installed independently via FreeBSD ports rather than the bundled code).  This is better for reliability and security anyway, since these ports are regularly maintained, while bundled code tends to be outdated.  We (FreeBSD port maintainers) generally unbundle as much as we can for these reasons, but I was pressed for time when I originally ported salmon.

**Comment by BenjaminDEMAILLE** [comment]
Glad unbundling libdivide/eigen3 got you unblocked, and agreed that unbundling maintained system libraries is the better long-term posture.

For the record, the current salmon line is a **Rust rewrite (v2.3.1)** with no libdivide/eigen3/clang C++ build at all, so clang-19 breakage doesn't apply there. Every release ships prebuilt binaries (Linux `x86_64`/`aarch64`, macOS `x86_64`/`arm64`) and it's in Homebrew core (`brew install salmon`, #1046). The 1.x line remains available as v1.12.1 for anyone who needs it.
