### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by BioDNA-Research** [COMBINE-lab/salmon#984]
Hello, while compiling Salmon on my Ubuntu 24.04 system (KDE-Plasma 5.27.12) (using GCC 13.3.0 and CMake 3.28.3), I ran into errors that prevented successful compilation. The error messages indicated that fixed-width integer types such as uint32_t and uint64_t were not declared. The compiler specifically mentioned that these types are defined in the standard header <cstdint> and suggested adding the missing include.

The compilation failures occurred in several files. In EffectiveLengthStats.hpp and its corresponding source file (EffectiveLengthStats.cpp), the code uses uint32_t for defining a dynamic Eigen vector type, but the header did not include <cstdint>, causing type errors. Similarly, in SalmonExceptions.hpp and SalmonExceptions.cpp, where exceptions make use of uint64_t for representing numeric values like the number of assigned fragments, the absence of <cstdint> led to further errors. Lastly, in SalmonConfig.hpp a constexpr value was defined with type uint32_t but also failed to compile due to the missing include for <cstdint>.

To resolve the issue, I modified a total of five files: EffectiveLengthStats.hpp, EffectiveLengthStats.cpp, SalmonExceptions.hpp, SalmonExceptions.cpp, and SalmonConfig.hpp. In each of these files, I added the include directive for <cstdint> at the appropriate location near the top of the file, ensuring that the compiler recognizes the fixed-width integer types. This change successfully eliminated the errors related to uint32_t and uint64_t, allowing the build process to proceed.

I would like to know if this approach is correct, and whether other developers have experienced similar compilation issues with Salmon. Feedback on whether these modifications should be integrated into the official codebase would be greatly appreciated.

**Comment by BioDNA-Research** [comment]
here the issue on the end: 

cc1: warning: command-line option ‘-Wno-reorder’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-Wno-deprecated-copy’ is valid for C++/ObjC++ but not for C
[ 67%] Building CXX object src/CMakeFiles/salmon_core.dir/TranscriptGroup.cpp.o
[ 68%] Building CXX object src/CMakeFiles/salmon_core.dir/EffectiveLengthStats.cpp.o
In file included from /home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp:1:
/home/flza10/Downloads/salmon-1.10.1/include/EffectiveLengthStats.hpp:11:34: error: ‘uint32_t’ was not declared in this scope
   11 |   using VectorXu = Eigen::Matrix<uint32_t, Eigen::Dynamic, 1>;
      |                                  ^~~~~~~~
/home/flza10/Downloads/salmon-1.10.1/include/EffectiveLengthStats.hpp:5:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
    4 | #include "Eigen/Dense"
  +++ |+#include <cstdint>
    5 | 
/home/flza10/Downloads/salmon-1.10.1/include/EffectiveLengthStats.hpp:11:61: error: template argument 1 is invalid
   11 |   using VectorXu = Eigen::Matrix<uint32_t, Eigen::Dynamic, 1>;
      |                                                             ^
/home/flza10/Downloads/salmon-1.10.1/include/EffectiveLengthStats.hpp:15:20: error: ‘uint32_t’ has not been declared
   15 |   void addFragment(uint32_t txID, uint32_t len, double logMass);
      |                    ^~~~~~~~
/home/flza10/Downloads/salmon-1.10.1/include/EffectiveLengthStats.hpp:15:35: error: ‘uint32_t’ has not been declared
   15 |   void addFragment(uint32_t txID, uint32_t len, double logMass);
      |                                   ^~~~~~~~
/home/flza10/Downloads/salmon-1.10.1/include/EffectiveLengthStats.hpp:16:3: error: ‘uint32_t’ does not name a type
   16 |   uint32_t getObservedCount(uint32_t txID);
      |   ^~~~~~~~
/home/flza10/Downloads/salmon-1.10.1/include/EffectiveLengthStats.hpp:16:3: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/flza10/Downloads/salmon-1.10.1/include/EffectiveLengthStats.hpp:17:37: error: ‘uint32_t’ has not been declared
   17 |   double getExpectedEffectiveLength(uint32_t txID);
      |                                     ^~~~~~~~
/home/flza10/Downloads/salmon-1.10.1/include/EffectiveLengthStats.hpp:25:3: error: ‘VectorXu’ does not name a type
   25 |   VectorXu counts_;
      |   ^~~~~~~~
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp: In constructor ‘EffectiveLengthStats::EffectiveLengthStats(size_t)’:
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp:6:7: error: class ‘EffectiveLengthStats’ does not have any field named ‘counts_’
    6 |       counts_(numTxps) {
      |       ^~~~~~~
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp:10:5: error: ‘counts_’ was not declared in this scope; did you mean ‘const’?
   10 |     counts_(i) = 0;
      |     ^~~~~~~
      |     const
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp: At global scope:
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp:14:6: error: variable or field ‘addFragment’ declared void
   14 | void EffectiveLengthStats::addFragment(uint32_t txID, uint32_t len,
      |      ^~~~~~~~~~~~~~~~~~~~
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp:14:40: error: ‘uint32_t’ was not declared in this scope
   14 | void EffectiveLengthStats::addFragment(uint32_t txID, uint32_t len,
      |                                        ^~~~~~~~
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp:3:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
    2 | #include "SalmonMath.hpp"
  +++ |+#include <cstdint>
    3 | 
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp:14:55: error: ‘uint32_t’ was not declared in this scope
   14 | void EffectiveLengthStats::addFragment(uint32_t txID, uint32_t len,
      |                                                       ^~~~~~~~
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp:14:55: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp:15:40: error: expected primary-expression before ‘double’
   15 |                                        double logMass) {
      |                                        ^~~~~~
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp:23:1: error: ‘uint32_t’ does not name a type
   23 | uint32_t EffectiveLengthStats::getObservedCount(uint32_t txID) {
      | ^~~~~~~~
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp:23:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp:27:8: error: ‘double EffectiveLengthStats::getExpectedEffectiveLength’ is not a static data member of ‘class EffectiveLengthStats’
   27 | double EffectiveLengthStats::getExpectedEffectiveLength(uint32_t txID) {
      |        ^~~~~~~~~~~~~~~~~~~~
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp:27:57: error: ‘uint32_t’ was not declared in this scope
   27 | double EffectiveLengthStats::getExpectedEffectiveLength(uint32_t txID) {
      |                                                         ^~~~~~~~
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp:27:57: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp: In member function ‘void EffectiveLengthStats::merge(const EffectiveLengthStats&)’:
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp:49:5: error: ‘counts_’ was not declared in this scope; did you mean ‘const’?
   49 |     counts_(i) = other.counts_(i);
      |     ^~~~~~~
      |     const
/home/flza10/Downloads/salmon-1.10.1/src/EffectiveLengthStats.cpp:49:24: error: ‘const class EffectiveLengthStats’ has no member named ‘counts_’
   49 |     counts_(i) = other.counts_(i);
      |                        ^~~~~~~
make[2]: *** [src/CMakeFiles/salmon_core.dir/build.make:132: src/CMakeFiles/salmon_core.dir/EffectiveLengthStats.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:597: src/CMakeFiles/salmon_core.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

**Comment by BenjaminDEMAILLE** [comment]
As @jashapiro noted, this `<cstdint>` build error is fixed in the later 1.x tags (it compiles on Ubuntu 24.04 with v1.10.3 / v1.12.1).

More broadly, the current line is the **Rust rewrite (v2.3.1)**, which drops the C++ toolchain entirely and ships prebuilt binaries for Linux/macOS × `x86_64`/`arm64`, plus `brew install salmon` (now in Homebrew core, #1046), so you can skip compiling altogether. The 1.x line remains available as v1.12.1 if you need it.
